### ISSUE TITLE
Implement hex_get_bytes function

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-math#1]
**HELP WANTED:** If you'd like to take this challenge on, please let me know! Even if you're new to Python and/or github, this is a great place to start and I'd be happy to help walk you through this challenge as much as you need - don't hesitate to ask.

---

I'd like to have a `hex_get_bytes` function added to [maths.py](https://github.com/democritus-project/democritus-math/blob/master/democritus_math/maths.py) that takes:

- a hex number (e.g. `0x12345678`)
- an integer representing the number of bytes of the hex number we want to return (e.g. `2`)

and will returns a hex number with the selected number of bytes (e.g. given `0x12345678` and `2`, the function would return `0x1234`).

### Basic Spec

I envision the function signature looking like:

```python
def hex_get_bytes(hex_number, number_of_bytes: int):
    ....
```

I'd like this function to be able to pass the following test:

```python
def test_hex_get_bytes_1():
    """."""
    assert hex_get_bytes(0x12345678, 2) == 0x1234
```

**Comment by zh-beep** [comment]
If this is issue is still open, would I be able to try it?

**Comment by fhightower** [comment]
Hi @zh-beep  - thanks for reaching out! Yes, this issue is still open and you are welcome to work on it.

Let me know if you have any questions and I'll be happy to help.

**Comment by zh-beep** [comment]
@fhightower Can I assume I wouldn't have to check the hex is correct? (it'll be in the correct format)

**Comment by fhightower** [comment]
> @fhightower Can I assume I wouldn't have to check the hex is correct? (it'll be in the correct format)

Good question! Yes, for the time being, let's just assume the given `hex_number` is correct.

**Comment by fhightower** [comment]
Hi @zh-beep 👋  ! Have you been able to make any progress on this issue? No worries if you haven't. Is there anything I can do to help?

**Comment by zh-beep** [comment]
Hi @fhightower - I have made some progress. I am able to bitshift the numbers, but am having trouble converting the resulting number back into an int with 0x in front of it. If I use: `hex(number)` it returns a string not an int. Would you have any advice?

**Comment by fhightower** [comment]
Good point. You can just return a string (something like `'0x1234'`) for now. I'm not sure if there is a good way to convert it to an int with `0x` in front of it.

**Comment by fhightower** [comment]
This is done 🎉
